-- IBIZA I WAS HERE — MVP data model
-- Apply to the dedicated project database when it is created.

create table if not exists public.memories (
  id uuid primary key default gen_random_uuid(),
  memory_number bigint generated by default as identity unique,
  public_slug text unique not null,
  participant_name text not null,
  memory_year smallint not null check (memory_year between 1900 and 2100),
  image_path text not null,
  image_width integer,
  image_height integer,
  dominant_r smallint,
  dominant_g smallint,
  dominant_b smallint,
  grid_x integer not null check (grid_x between 0 and 999),
  grid_y integer not null check (grid_y between 0 and 999),
  position_x double precision not null check (position_x >= 0 and position_x <= 1),
  position_y double precision not null check (position_y >= 0 and position_y <= 1),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','refunded','waived')),
  publish_status text not null default 'draft' check (publish_status in ('draft','published','hidden')),
  payment_provider text,
  payment_reference text,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  published_at timestamptz,
  unique (grid_x, grid_y)
);

create index if not exists memories_public_lookup
  on public.memories (public_slug)
  where publish_status = 'published';

create index if not exists memories_artwork_positions
  on public.memories (grid_x, grid_y)
  where publish_status = 'published';

alter table public.memories enable row level security;

-- Public visitors may only read memories that are published.
create policy "published memories are public"
  on public.memories for select
  using (publish_status = 'published');

-- Uploads and writes will go through server-side routes / service role.
-- No anonymous INSERT/UPDATE/DELETE policy is intentionally created.
