"use client";
import {useEffect,useState} from "react";
const copy={
en:{title:"PRIVACY POLICY",intro:"How we use personal data when you visit or participate in WE ARE SUPERSONICOS.",sections:[
["Controller",<>Sonica Broadcast 5.0 SL, NIF / CIF B57754228, Carretera Eivissa-Sant Antoni, Km 7.200, Nav 1, 07820, Sant Antoni de Portmany, Illes Balears, España. Contact: <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a>.</>],
["Data we process","Depending on how you use the project, we may process your name, email address, memory year, submitted photograph, Memory number and URL, technical and security information, consent records and, when payment is activated, transaction references and information required to administer the participation. Your email address is not displayed publicly."],
["Why we use it","We process data to operate the collective artwork, create and publish your Memory, provide its permanent URL and Passport, send and recover your Memory, moderate submissions, protect the service, respond to rights or takedown requests, comply with legal obligations and administer payments when enabled."],
["Legal bases","Processing necessary to provide the participation is based on the relationship created when you submit a Memory and accept the Terms. Specific permissions and licences are recorded through the participation flow. Legal obligations may require additional processing. Non-essential analytics is used only where the required consent has been obtained."],
["Public nature of a Memory","A published Memory is intentionally public and may include the photograph, participant name, year, Memory number and its public URL. Your email address and payment references are not public. Do not submit information you do not want to form part of the public artwork."],
["Service providers and transfers","We use technology providers to host, store, secure, deliver and analyse the service and to administer payments and transactional communications. Where a provider processes personal data on our behalf, we require appropriate data-protection safeguards. Where processing involves an international transfer, the applicable transfer mechanism and safeguards must be used."],
["Retention","Published Memories are intended to remain part of the artwork for the life of the project, subject to valid removal requests, legal obligations and the Terms. Operational, security, consent, contact and transaction records are retained only for the periods necessary for their purpose or required by law."],
["Your rights",<>You may request access, rectification, erasure, restriction, portability or objection where applicable, and withdraw consent where processing is based on consent. Contact <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a>. You may also lodge a complaint with the Spanish Data Protection Agency.</>],
["Image moderation","Submitted images may be subject to automated safety checks designed to identify prohibited or high-risk content. Ambiguous content may be held for review. The project does not accept identifiable minors or sexually explicit, pornographic, graphic violent, hateful, threatening or clearly abusive content. Normal beach, swimwear, pool and nightlife imagery is permitted."],
["Security","We apply technical and organisational measures appropriate to the risks of the service and review them as the project evolves."],
["Changes","We may update this policy when the service, providers or legal requirements change. The current version will always be published here."]]},
es:{title:"POLÍTICA DE PRIVACIDAD",intro:"Cómo utilizamos los datos personales cuando visitas o participas en WE ARE SUPERSONICOS.",sections:[
["Responsable del tratamiento",<>Sonica Broadcast 5.0 SL, NIF / CIF B57754228, Carretera Eivissa-Sant Antoni, Km 7.200, Nav 1, 07820, Sant Antoni de Portmany, Illes Balears, España. Contacto: <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a>.</>],
["Datos que tratamos","Dependiendo de cómo utilices el proyecto, podemos tratar tu nombre, dirección de email, año de la memoria, fotografía enviada, número y URL de la Memoria, información técnica y de seguridad, registros de consentimiento y, cuando el pago esté activado, referencias de transacción e información necesaria para gestionar la participación. Tu dirección de email no se muestra públicamente."],
["Para qué los utilizamos","Tratamos los datos para operar la obra colectiva, crear y publicar tu Memoria, proporcionar su URL permanente y Passport, enviarte y permitirte recuperar tu Memoria, moderar contenidos, proteger el servicio, responder a solicitudes de derechos o retirada, cumplir obligaciones legales y gestionar los pagos cuando estén habilitados."],
["Bases jurídicas","El tratamiento necesario para prestar el servicio de participación se basa en la relación creada cuando envías una Memoria y aceptas los Términos. Los permisos y licencias específicos quedan registrados mediante el proceso de participación. Las obligaciones legales pueden exigir tratamientos adicionales. Las analíticas no esenciales solo se utilizan cuando se ha obtenido el consentimiento requerido."],
["Carácter público de una Memoria","Una Memoria publicada es intencionadamente pública y puede incluir la fotografía, nombre del participante, año, número de Memoria y su URL pública. Tu dirección de email y las referencias de pago no son públicas. No envíes información que no quieras que forme parte de la obra pública."],
["Proveedores y transferencias","Utilizamos proveedores tecnológicos para alojar, almacenar, proteger, distribuir y analizar el servicio, así como para gestionar pagos y comunicaciones transaccionales. Cuando un proveedor trata datos personales por nuestra cuenta, exigimos las garantías adecuadas de protección de datos. Cuando el tratamiento implique una transferencia internacional, se utilizarán el mecanismo y las garantías aplicables."],
["Conservación","Las Memorias publicadas están destinadas a permanecer en la obra durante la vida del proyecto, sujetas a solicitudes válidas de retirada, obligaciones legales y los Términos. Los registros operativos, de seguridad, consentimiento, contacto y transacción se conservan únicamente durante los periodos necesarios para su finalidad o exigidos por ley."],
["Tus derechos",<>Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición cuando corresponda, y retirar el consentimiento cuando el tratamiento se base en él. Contacta con <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a>. También puedes presentar una reclamación ante la Agencia Española de Protección de Datos.</>],
["Moderación de imágenes","Las imágenes enviadas pueden someterse a controles automáticos de seguridad destinados a identificar contenido prohibido o de alto riesgo. El contenido ambiguo puede quedar pendiente de revisión. El proyecto no acepta menores identificables ni contenido sexualmente explícito, pornográfico, violencia gráfica, odio, amenazas o contenido claramente abusivo. Se permiten imágenes normales de playa, baño, piscina y vida nocturna."],
["Seguridad","Aplicamos medidas técnicas y organizativas adecuadas a los riesgos del servicio y las revisamos a medida que evoluciona el proyecto."],
["Cambios","Podemos actualizar esta política cuando cambien el servicio, los proveedores o los requisitos legales. La versión vigente estará siempre publicada aquí."]}};
export default function Page(){const[lang,setLang]=useState("en");useEffect(()=>setLang(localStorage.getItem("supersonicos-lang")||"en"),[]);const c=copy[lang];return <main className="legalPage"><a className="legalBack" href="/">← WE ARE SUPERSONICOS</a><h1>{c.title}</h1><p className="legalIntro">{c.intro}</p>{c.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</main>}