"use client";
import {useEffect,useState} from "react";

const ES={
"OVERVIEW":"INICIO","ABOUT":"SOBRE EL PROYECTO","FIND MY MEMORY":"ENCONTRAR MI MEMORIA","ADD YOUR MEMORY":"AÑADE TU MEMORIA","MENU":"MENÚ",
"A COLLECTIVE MEMORY PROJECT":"UN PROYECTO DE MEMORIA COLECTIVA","20 YEARS.":"20 AÑOS.","20,000 MEMORIES.":"20.000 MEMORIAS.","ONE SOUND.":"UN SONIDO.",
"Every memory finds its place.":"Cada memoria encuentra su lugar.","The first memory":"La primera memoria","is waiting.":"está esperando.","EXPLORE THE IMAGE ↓":"EXPLORA LA IMAGEN ↓",
"ABOUT THE ARTWORK":"SOBRE LA OBRA","IBIZA SONICA · 20 YEARS":"IBIZA SONICA · 20 AÑOS",
"Twenty years of Ibiza Sonica, told through the people who listened, danced, broadcast, travelled and shared the sound with us. 20,000 real memories becoming one collective image.":"Veinte años de Ibiza Sonica contados a través de las personas que escucharon, bailaron, emitieron, viajaron y compartieron el sonido con nosotros. 20.000 memorias reales convirtiéndose en una imagen colectiva.",
"CHOOSE A MEMORY.":"ELIGE UNA MEMORIA.","One photograph from a moment that connects you to Ibiza Sonica. A broadcast, a party, a journey, a song, a place or simply a moment you still remember.":"Una fotografía de un momento que te conecte con Ibiza Sonica. Una emisión, una fiesta, un viaje, una canción, un lugar o simplemente un momento que todavía recuerdes.",
"FIND YOUR PLACE.":"ENCUENTRA TU LUGAR.","For €1, your photograph receives one equal position in the artwork. Every SUPERSONICO has the same space. No premium positions. No hierarchy.":"Por 1 €, tu fotografía recibe un lugar igual dentro de la obra. Cada SUPERSONICO tiene el mismo espacio. Sin posiciones premium. Sin jerarquías.",
"BECOME PART OF THE IMAGE.":"FORMA PARTE DE LA IMAGEN.","Step back and you see one image of Ibiza Sonica. Move closer and it opens into the people, years and moments that made twenty years of sound.":"Aléjate y verás una imagen de Ibiza Sonica. Acércate y aparecerán las personas, los años y los momentos que construyeron veinte años de sonido.",
"COMPLETE THE ARTWORK.":"COMPLETA LA OBRA.","Memory by memory, the image gives way to the community inside it. The artwork is complete when Memory #20,000 finds its place.":"Memoria a memoria, la imagen deja paso a la comunidad que contiene. La obra estará completa cuando la Memoria #20.000 encuentre su lugar.",
"A living archive of the people who made Ibiza Sonica part of their lives, wherever in the world they listened.":"Un archivo vivo de las personas que hicieron de Ibiza Sonica parte de sus vidas, desde cualquier lugar del mundo.",
"BEFORE YOU TAKE PART":"ANTES DE PARTICIPAR","PARTICIPATION":"NORMAS DE","RULES.":"PARTICIPACIÓN.",
"WE ARE SUPERSONICOS is built from real memories shared by real people. These rules protect the artwork and everyone who becomes part of it.":"WE ARE SUPERSONICOS se construye con memorias reales compartidas por personas reales. Estas normas protegen la obra y a todas las personas que forman parte de ella.",
"YOUR PHOTO.":"TU FOTO.","You must own the photograph or have the right to share it.":"Debes ser propietario de la fotografía o tener derecho a compartirla.",
"PEOPLE IN YOUR PHOTO.":"PERSONAS EN TU FOTO.","You must have the necessary permission to publish identifiable people appearing in the photograph.":"Debes tener el permiso necesario para publicar a las personas identificables que aparezcan en la fotografía.",
"NO MINORS.":"SIN MENORES.","Photographs containing identifiable minors are not accepted.":"No se aceptan fotografías con menores identificables.",
"NO EXPLICIT SEXUAL CONTENT.":"SIN CONTENIDO SEXUAL EXPLÍCITO.","Sexually explicit or pornographic material is not accepted. Swimwear, beach, pool and normal nightlife imagery are welcome.":"No se acepta material sexualmente explícito o pornográfico. Sí se permiten imágenes normales de bañadores, playa, piscina y vida nocturna.",
"NO GRAPHIC OR ABUSIVE CONTENT.":"SIN CONTENIDO GRÁFICO O ABUSIVO.","Graphic violence, hateful, threatening or clearly abusive material is not accepted.":"No se acepta violencia gráfica ni material de odio, amenazante o claramente abusivo.",
"AUTOMATIC MODERATION.":"MODERACIÓN AUTOMÁTICA.","Images may be automatically checked before publication. Content may be rejected or held for review when necessary.":"Las imágenes pueden comprobarse automáticamente antes de publicarse. El contenido puede rechazarse o quedar pendiente de revisión cuando sea necesario.",
"ONE REAL MEMORY.":"UNA MEMORIA REAL.","Submit a genuine photograph connected to your experience of Ibiza Sonica.":"Envía una fotografía real conectada con tu experiencia de Ibiza Sonica.",
"By participating, you agree to these rules and to the Terms of Participation and Privacy Policy.":"Al participar, aceptas estas normas, los Términos de Participación y la Política de Privacidad.",
"QUESTIONS ABOUT THE ARTWORK":"PREGUNTAS SOBRE LA OBRA","WHAT IS WE ARE SUPERSONICOS?":"¿QUÉ ES WE ARE SUPERSONICOS?","WHAT KIND OF PHOTO CAN I ADD?":"¿QUÉ TIPO DE FOTO PUEDO AÑADIR?","DOES IT COST ANYTHING?":"¿CUÁNTO CUESTA?","WHAT HAPPENS AFTER I ADD MY PHOTO?":"¿QUÉ PASA DESPUÉS DE AÑADIR MI FOTO?","WHAT IS THE PASSPORT?":"¿QUÉ ES EL PASSPORT?","WHAT DOES SHARE DO?":"¿QUÉ HACE SHARE?","HOW IS MY PLACE CHOSEN?":"¿CÓMO SE ELIGE MI LUGAR?","WHAT HAPPENS WHEN IT REACHES 20,000?":"¿QUÉ PASA CUANDO LLEGUE A 20.000?",
"A collective digital artwork made from 20,000 real memories from the Ibiza Sonica community around the world. Each photograph becomes one equal part of a single image celebrating 20 years of Ibiza Sonica.":"Una obra digital colectiva creada con 20.000 memorias reales de la comunidad de Ibiza Sonica en todo el mundo. Cada fotografía se convierte en una parte igual de una única imagen que celebra 20 años de Ibiza Sonica.",
"Any photograph connected to a real memory of Ibiza Sonica. It can come from Ibiza or anywhere the sound travelled with you, and it can be recent or decades old.":"Cualquier fotografía conectada con una memoria real de Ibiza Sonica. Puede ser de Ibiza o de cualquier lugar al que el sonido haya viajado contigo, reciente o de hace décadas.",
"Yes. Adding one memory costs €1. One euro gives your photograph one equal place in the artwork. No premium positions, no larger spaces, no hierarchy.":"Sí. Añadir una memoria cuesta 1 €. Un euro da a tu fotografía un lugar igual en la obra. Sin posiciones premium, espacios mayores ni jerarquías.",
"Your memory receives its own number and position inside the artwork. You can return directly to it through its individual URL.":"Tu memoria recibe su propio número y posición dentro de la obra. Puedes volver directamente a ella mediante su URL individual.",
"Your Passport is the personal visual record of your participation: your photograph, name, year and unique Memory number. It is designed to be saved and shared.":"Tu Passport es el registro visual personal de tu participación: tu fotografía, nombre, año y número único de Memoria. Está diseñado para guardarlo y compartirlo.",
"SHARE creates a direct link to your memory inside the artwork, so other people can find your exact place — and add their own memory.":"SHARE crea un enlace directo a tu memoria dentro de la obra para que otras personas encuentren tu lugar exacto y puedan añadir su propia memoria.",
"Every memory has an equal-sized position. The final system places photographs according to visual characteristics such as colour and light so that, together, they reconstruct the master image of Ibiza Sonica.":"Cada memoria ocupa un espacio del mismo tamaño. El sistema coloca las fotografías según características visuales como el color y la luz para que, juntas, reconstruyan la imagen maestra de Ibiza Sonica.",
"The artwork is complete. The Ibiza Sonica Master Image has been progressively replaced by 20,000 real memories from the Ibiza Sonica community — while remaining visible from a distance through those memories.":"La obra queda completa. La imagen maestra de Ibiza Sonica habrá sido sustituida progresivamente por 20.000 memorias reales de su comunidad, manteniéndose visible desde la distancia a través de esas memorias.",
"TERMS":"TÉRMINOS","PRIVACY":"PRIVACIDAD","COOKIES":"COOKIES","LEGAL":"LEGAL","REMOVAL":"RETIRADA","FIT IMAGE":"AJUSTAR IMAGEN",
"LEGAL NOTICE":"AVISO LEGAL","PRIVACY POLICY":"POLÍTICA DE PRIVACIDAD","TERMS OF PARTICIPATION":"TÉRMINOS DE PARTICIPACIÓN","COOKIE POLICY":"POLÍTICA DE COOKIES","REMOVAL & TAKEDOWN":"RETIRADA DE CONTENIDO",
"Operator":"Titular","Website":"Sitio web","Intellectual property":"Propiedad intelectual","Applicable law":"Legislación aplicable","Controller":"Responsable del tratamiento","Data we process":"Datos que tratamos","Why we use it":"Finalidades","Legal bases":"Bases jurídicas","Public nature of a Memory":"Carácter público de una Memoria","Service providers and transfers":"Proveedores y transferencias","Retention":"Conservación","Your rights":"Tus derechos","Image moderation":"Moderación de imágenes","Security":"Seguridad","Changes":"Cambios",
"The project":"El proyecto","Your contribution":"Tu aportación","Your rights and permissions":"Tus derechos y permisos","Participation Rules":"Normas de participación","Moderation":"Moderación","Placement":"Colocación","Removal":"Retirada","Price and payment":"Precio y pago",
"Essential technologies":"Tecnologías esenciales","Analytics":"Analítica","Your choice":"Tu elección","Updates":"Actualizaciones","When to contact us":"Cuándo contactar","What to send":"Qué enviar","What happens next":"Qué ocurre después","Urgent safety concerns":"Cuestiones urgentes de seguridad"
};
Object.assign(ES,{
"Information about the operator of WE ARE SUPERSONICOS.":"Información sobre el titular de WE ARE SUPERSONICOS.",
"WE ARE SUPERSONICOS is operated by Sonica Broadcast 5.0 SL, NIF / CIF B57754228, a Sociedad Limitada Unipersonal, with registered address at Carretera Eivissa-Sant Antoni, Km 7.200, Nav 1, 07820, Sant Antoni de Portmany, Illes Balears, España.":"WE ARE SUPERSONICOS está operado por Sonica Broadcast 5.0 SL, NIF / CIF B57754228, Sociedad Limitada Unipersonal, con domicilio social en Carretera Eivissa-Sant Antoni, Km 7.200, Nav 1, 07820, Sant Antoni de Portmany, Illes Balears, España.",
"Mercantile Registry details will be added once verified.":"Los datos del Registro Mercantil se añadirán una vez verificados.",
"This notice applies to supersonicos.ibizasonica.com and the services made available through it.":"Este aviso se aplica a supersonicos.ibizasonica.com y a los servicios ofrecidos a través de este sitio.",
"The project name, visual identity, website, software, texts and project materials are protected by applicable intellectual property rules. Participant photographs remain subject to the rights described in the Terms of Participation.":"El nombre del proyecto, la identidad visual, el sitio web, el software, los textos y los materiales del proyecto están protegidos por la normativa aplicable de propiedad intelectual. Las fotografías de los participantes quedan sujetas a los derechos descritos en los Términos de Participación.",
"This website is operated from Spain and is subject to applicable Spanish and European Union law.":"Este sitio web se opera desde España y está sujeto a la legislación española y de la Unión Europea aplicable.",
"How we use personal data when you visit or participate in WE ARE SUPERSONICOS.":"Cómo utilizamos los datos personales cuando visitas o participas en WE ARE SUPERSONICOS.",
"Depending on how you use the project, we may process your name, memory year, submitted photograph, Memory number and URL, technical and security information, consent records and, when payment is activated, transaction references and information required to administer the participation. We do not need your photograph for unrelated advertising purposes.":"Según cómo utilices el proyecto, podremos tratar tu nombre, el año de la memoria, la fotografía enviada, el número y la URL de la Memoria, información técnica y de seguridad, registros de consentimiento y, cuando se active el pago, referencias de transacción e información necesaria para gestionar la participación. No utilizamos tu fotografía para fines publicitarios ajenos al proyecto.",
"We process data to operate the collective artwork, create and publish your Memory, provide its permanent URL and Passport, moderate submissions, protect the service, respond to rights or takedown requests, comply with legal obligations and administer payments when enabled.":"Tratamos los datos para operar la obra colectiva, crear y publicar tu Memoria, proporcionar su URL permanente y Passport, moderar los envíos, proteger el servicio, atender solicitudes de derechos o retirada, cumplir obligaciones legales y gestionar los pagos cuando estén activados.",
"Processing necessary to provide the participation is based on the relationship created when you submit a Memory and accept the Terms. Specific permissions and licences are recorded through the participation flow. Legal obligations may require additional processing. Non-essential analytics is used only where the required consent has been obtained.":"El tratamiento necesario para prestar el servicio de participación se basa en la relación creada cuando envías una Memoria y aceptas los Términos. Los permisos y licencias específicos se registran durante el proceso de participación. Las obligaciones legales pueden requerir tratamientos adicionales. La analítica no esencial solo se utiliza cuando se ha obtenido el consentimiento requerido.",
"A published Memory is intentionally public and may include the photograph, participant name, year, Memory number and its public URL. Do not submit information you do not want to form part of the public artwork.":"Una Memoria publicada es deliberadamente pública y puede incluir la fotografía, el nombre del participante, el año, el número de Memoria y su URL pública. No envíes información que no quieras que forme parte de la obra pública.",
"We use technology providers to host, store, secure, deliver and analyse the service. Where a provider processes personal data on our behalf, we require appropriate data-protection safeguards. Where processing involves an international transfer, the applicable transfer mechanism and safeguards must be used.":"Utilizamos proveedores tecnológicos para alojar, almacenar, proteger, distribuir y analizar el servicio. Cuando un proveedor trata datos personales por nuestra cuenta, exigimos las garantías adecuadas de protección de datos. Cuando el tratamiento implica una transferencia internacional, se aplicarán el mecanismo y las garantías correspondientes.",
"Published Memories are intended to remain part of the artwork for the life of the project, subject to valid removal requests, legal obligations and the Terms. Operational, security, consent and transaction records are retained only for the periods necessary for their purpose or required by law.":"Las Memorias publicadas están destinadas a permanecer en la obra durante la vida del proyecto, salvo solicitudes válidas de retirada, obligaciones legales y lo dispuesto en los Términos. Los registros operativos, de seguridad, consentimiento y transacciones se conservan únicamente durante el tiempo necesario para su finalidad o exigido por ley.",
"You may request access, rectification, erasure, restriction, portability or objection where applicable, and withdraw consent where processing is based on consent. Contact hello@ibizasonica.com. You may also lodge a complaint with the Spanish Data Protection Agency.":"Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición cuando corresponda, y retirar el consentimiento cuando el tratamiento se base en él. Contacta con hello@ibizasonica.com. También puedes presentar una reclamación ante la Agencia Española de Protección de Datos.",
"Submitted images may be subject to automated safety checks designed to identify prohibited or high-risk content. Ambiguous content may be held for review. The project does not accept identifiable minors or sexually explicit, pornographic, graphic violent, hateful, threatening or clearly abusive content. Normal beach, swimwear, pool and nightlife imagery is permitted.":"Las imágenes enviadas pueden someterse a controles automáticos de seguridad para identificar contenido prohibido o de alto riesgo. El contenido ambiguo puede quedar pendiente de revisión. El proyecto no acepta menores identificables ni contenido sexualmente explícito, pornográfico, de violencia gráfica, de odio, amenazante o claramente abusivo. Se permiten imágenes normales de playa, bañadores, piscina y vida nocturna.",
"We apply technical and organisational measures appropriate to the risks of the service and review them as the project evolves.":"Aplicamos medidas técnicas y organizativas adecuadas a los riesgos del servicio y las revisamos a medida que evoluciona el proyecto.",
"We may update this policy when the service, providers or legal requirements change. The current version will always be published here.":"Podremos actualizar esta política cuando cambien el servicio, los proveedores o los requisitos legales. La versión vigente estará siempre publicada aquí.",
"The rules that apply when you add a Memory to the collective artwork.":"Las normas aplicables cuando añades una Memoria a la obra colectiva.",
"WE ARE SUPERSONICOS is a collective digital artwork designed to be formed by 20,000 real memories from the Ibiza Sonica community. Each accepted Memory receives one equal-sized position. No participant can buy a larger, premium or privileged position.":"WE ARE SUPERSONICOS es una obra digital colectiva diseñada para estar formada por 20.000 memorias reales de la comunidad de Ibiza Sonica. Cada Memoria aceptada recibe un espacio del mismo tamaño. Ningún participante puede comprar una posición mayor, premium o privilegiada.",
"You submit one photograph connected to a genuine experience of Ibiza Sonica, together with the requested participant information. You are responsible for the submission and for the accuracy of the information you provide.":"Envías una fotografía conectada con una experiencia real de Ibiza Sonica junto con la información solicitada del participante. Eres responsable del envío y de la exactitud de la información que proporcionas.",
"You retain the rights you hold in your photograph. By submitting it, you confirm that you own it or otherwise have the rights needed to share it and that you have the necessary permissions for identifiable people shown in it.":"Conservas los derechos que tengas sobre tu fotografía. Al enviarla, confirmas que eres su propietario o que dispones de los derechos necesarios para compartirla y que cuentas con los permisos necesarios de las personas identificables que aparezcan en ella.",
"You grant Sonica Broadcast 5.0 SL a non-exclusive licence to host, store, technically adapt, resize, crop, reproduce, display and communicate the photograph as part of WE ARE SUPERSONICOS, its mosaic, Memory page, Passport and communications whose purpose is to present, document or promote the project. This licence does not transfer ownership of your photograph to us.":"Concedes a Sonica Broadcast 5.0 SL una licencia no exclusiva para alojar, almacenar, adaptar técnicamente, redimensionar, recortar, reproducir, mostrar y comunicar la fotografía como parte de WE ARE SUPERSONICOS, su mosaico, la página de la Memoria, el Passport y las comunicaciones destinadas a presentar, documentar o promocionar el proyecto. Esta licencia no nos transfiere la propiedad de tu fotografía.",
"Identifiable minors are not accepted. Sexually explicit or pornographic content is not accepted. Normal swimwear, beach, pool and nightlife imagery is permitted. Graphic violence, hateful, threatening or clearly abusive content is not accepted. We may reject, suspend or remove submissions that breach these rules, infringe rights or create a material safety or legal risk.":"No se aceptan menores identificables ni contenido sexualmente explícito o pornográfico. Se permiten imágenes normales de bañadores, playa, piscina y vida nocturna. No se acepta violencia gráfica ni contenido de odio, amenazante o claramente abusivo. Podemos rechazar, suspender o retirar envíos que incumplan estas normas, vulneren derechos o generen un riesgo material de seguridad o legal.",
"Submissions may be checked automatically and, where necessary, manually. Automated checks are a safety measure and do not remove your responsibility for the content you submit or the rights required to publish it.":"Los envíos pueden comprobarse automáticamente y, cuando sea necesario, manualmente. Los controles automáticos son una medida de seguridad y no eliminan tu responsabilidad sobre el contenido enviado ni sobre los derechos necesarios para publicarlo.",
"The project determines the position of each accepted Memory. Placement may use visual characteristics such as colour and light so that the Memories collectively reconstruct the Master Image. Equal position means equal visual space, not a right to choose a particular location.":"El proyecto determina la posición de cada Memoria aceptada. La colocación puede utilizar características visuales como el color y la luz para que las Memorias reconstruyan colectivamente la Imagen Maestra. Igual posición significa igual espacio visual, no el derecho a elegir una ubicación concreta.",
"You or another rights holder may submit a removal request. We may ask for enough information to identify the Memory and verify the request. Removal from public display does not require us to erase records that we must retain by law or that are necessary to establish, exercise or defend legal claims.":"Tú u otro titular de derechos podéis presentar una solicitud de retirada. Podemos pedir información suficiente para identificar la Memoria y verificar la solicitud. La retirada de la exhibición pública no nos obliga a borrar registros que debamos conservar por ley o que sean necesarios para formular, ejercer o defender reclamaciones.",
"When paid participation is activated, the price shown before payment will be the price applicable to that submission, together with information required by law about applicable taxes.":"Cuando se active la participación de pago, el precio mostrado antes del pago será el aplicable a ese envío, junto con la información legalmente exigida sobre los impuestos correspondientes.",
"The project is operated by Sonica Broadcast 5.0 SL, NIF / CIF B57754228. Contact: hello@ibizasonica.com.":"El proyecto está operado por Sonica Broadcast 5.0 SL, NIF / CIF B57754228. Contacto: hello@ibizasonica.com.",
"Information about cookies and similar technologies used on WE ARE SUPERSONICOS.":"Información sobre las cookies y tecnologías similares utilizadas en WE ARE SUPERSONICOS.",
"Technologies strictly necessary to provide, secure or remember essential functions of the website may operate without optional analytics consent where permitted by law.":"Las tecnologías estrictamente necesarias para prestar, proteger o recordar funciones esenciales del sitio web pueden funcionar sin consentimiento para analítica opcional cuando la ley lo permita.",
"WE ARE SUPERSONICOS uses Google Analytics to understand aggregate use of the website. Analytics is not activated until the visitor has given the consent required for non-essential analytics technologies.":"WE ARE SUPERSONICOS utiliza Google Analytics para comprender de forma agregada el uso del sitio web. La analítica no se activa hasta que el visitante haya dado el consentimiento requerido para tecnologías analíticas no esenciales.",
"On your first visit you can accept or reject optional analytics with choices presented at the same level. You can change your choice later through Cookie Settings.":"En tu primera visita puedes aceptar o rechazar la analítica opcional mediante opciones presentadas al mismo nivel. Puedes cambiar tu elección posteriormente desde Configuración de cookies.",
"This policy will be updated if the technologies or providers used by the project change.":"Esta política se actualizará si cambian las tecnologías o los proveedores utilizados por el proyecto.",
"A direct route to report a Memory or request that content be removed.":"Una vía directa para denunciar una Memoria o solicitar la retirada de contenido.",
"Contact us if you submitted a Memory and want to request its removal, if you are identifiable in a photograph and believe it should not be published, if you own rights in a photograph used without permission, or if a Memory appears to breach the Participation Rules.":"Contacta con nosotros si enviaste una Memoria y quieres solicitar su retirada, si eres identificable en una fotografía y consideras que no debería publicarse, si eres titular de derechos sobre una fotografía utilizada sin permiso o si una Memoria parece incumplir las Normas de Participación.",
"Email hello@ibizasonica.com with the subject “WE ARE SUPERSONICOS · Removal request”. Include the Memory number or URL, the reason for the request and enough information for us to understand and, where necessary, verify your connection to the content.":"Escribe a hello@ibizasonica.com con el asunto «WE ARE SUPERSONICOS · Solicitud de retirada». Incluye el número o URL de la Memoria, el motivo de la solicitud y suficiente información para que podamos comprender y, cuando sea necesario, verificar tu relación con el contenido.",
"We will assess the request and may temporarily restrict a Memory while it is reviewed. We may ask for additional information where reasonably necessary. Valid requests will be acted on in accordance with applicable law and the project's legal obligations.":"Evaluaremos la solicitud y podremos restringir temporalmente una Memoria mientras se revisa. Podremos solicitar información adicional cuando sea razonablemente necesario. Las solicitudes válidas se atenderán de acuerdo con la legislación aplicable y las obligaciones legales del proyecto.",
"If the report concerns a minor, sexual exploitation, credible threats or other urgent safety concerns, state that clearly in the subject and message so it can be prioritised.":"Si la denuncia afecta a un menor, explotación sexual, amenazas creíbles u otras cuestiones urgentes de seguridad, indícalo claramente en el asunto y en el mensaje para que pueda priorizarse.",
"YOUR PRIVACY.":"TU PRIVACIDAD.","We use optional analytics to understand how WE ARE SUPERSONICOS is used. You can accept or reject analytics. Essential technologies remain active.":"Utilizamos analítica opcional para comprender cómo se utiliza WE ARE SUPERSONICOS. Puedes aceptar o rechazarla. Las tecnologías esenciales permanecen activas.",
"Cookie Policy":"Política de cookies","REJECT":"RECHAZAR","ACCEPT":"ACEPTAR","COOKIE SETTINGS.":"CONFIGURACIÓN DE COOKIES.","COOKIE SETTINGS":"CONFIGURACIÓN DE COOKIES"
});
Object.assign(ES,{
"Contact:":"Contacto:",
"You may request access, rectification, erasure, restriction, portability or objection where applicable, and withdraw consent where processing is based on consent. Contact ":"Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oposición cuando corresponda, y retirar el consentimiento cuando el tratamiento se base en él. Contacta con ",
". You may also lodge a complaint with the Spanish Data Protection Agency.":". También puedes presentar una reclamación ante la Agencia Española de Protección de Datos.",
"The project is operated by Sonica Broadcast 5.0 SL, NIF / CIF B57754228. Contact: ":"El proyecto está operado por Sonica Broadcast 5.0 SL, NIF / CIF B57754228. Contacto: ",
"Email ":"Escribe a ",
" with the subject “WE ARE SUPERSONICOS · Removal request”. Include the Memory number or URL, the reason for the request and enough information for us to understand and, where necessary, verify your connection to the content.":" con el asunto «WE ARE SUPERSONICOS · Solicitud de retirada». Incluye el número o URL de la Memoria, el motivo de la solicitud y suficiente información para que podamos comprender y, cuando sea necesario, verificar tu relación con el contenido.",
"Analytics is currently ":"La analítica está actualmente ",
"accepted":"aceptada","rejected":"rechazada",". You can change your choice at any time.":". Puedes cambiar tu elección en cualquier momento."
});
const originals=new WeakMap();
function walk(root,lang){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
 let n;while(n=walker.nextNode()){
  if(!originals.has(n)) originals.set(n,n.nodeValue);
  const en=originals.get(n),key=en.trim();
  if(lang==="es"&&ES[key]) n.nodeValue=en.replace(key,ES[key]); else n.nodeValue=en;
 }
 document.documentElement.lang=lang;
}
export default function LanguageToggle(){
 const [lang,setLang]=useState("en");
 useEffect(()=>{
  const saved=localStorage.getItem("supersonicos-lang")||"en";
  setLang(saved);
  const sync=e=>{if(e.detail==="en"||e.detail==="es")setLang(e.detail)};
  window.addEventListener("supersonicos-language",sync);
  return()=>window.removeEventListener("supersonicos-language",sync);
 },[]);
 useEffect(()=>{walk(document.body,lang);localStorage.setItem("supersonicos-lang",lang);const o=new MutationObserver(()=>walk(document.body,lang));o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[lang]);
 const choose=next=>{setLang(next);localStorage.setItem("supersonicos-lang",next);window.dispatchEvent(new CustomEvent("supersonicos-language",{detail:next}))};
 return <div className="languageToggle" aria-label="Language"><button className={lang==="en"?"active":""} onClick={()=>choose("en")}>EN</button><span>/</span><button className={lang==="es"?"active":""} onClick={()=>choose("es")}>ES</button></div>
}