"use client";
import {useEffect,useState} from "react";
const copy={
en:{title:"TERMS OF PARTICIPATION",intro:"The rules that apply when you add a Memory to the collective artwork.",sections:[
["The project","WE ARE SUPERSONICOS is a collective digital artwork designed to be formed by 20,000 real memories from the Ibiza Sonica community. Each accepted Memory receives one equal-sized position. No participant can buy a larger, premium or privileged position."],
["Your contribution","You submit one photograph connected to a genuine experience of Ibiza Sonica, together with the requested participant information. You are responsible for the submission and for the accuracy of the information you provide."],
["Your rights and permissions",<>You retain the rights you hold in your photograph. By submitting it, you confirm that you own it or otherwise have the rights needed to share it and that you have the necessary permissions for identifiable people shown in it.<br/><br/>You grant Sonica Broadcast 5.0 SL a non-exclusive licence to host, store, technically adapt, resize, crop, reproduce, display and communicate the photograph as part of WE ARE SUPERSONICOS, its mosaic, Memory page, Passport and communications whose purpose is to present, document or promote the project. This licence does not transfer ownership of your photograph to us.</>],
["Participation Rules","Identifiable minors are not accepted. Sexually explicit or pornographic content is not accepted. Normal swimwear, beach, pool and nightlife imagery is permitted. Graphic violence, hateful, threatening or clearly abusive content is not accepted. We may reject, suspend or remove submissions that breach these rules, infringe rights or create a material safety or legal risk."],
["Moderation","Submissions may be checked automatically and, where necessary, manually. Automated checks are a safety measure and do not remove your responsibility for the content you submit or the rights required to publish it."],
["Placement","The project determines the position of each accepted Memory. Placement may use visual characteristics such as colour and light so that the Memories collectively reconstruct the Master Image. Equal position means equal visual space, not a right to choose a particular location."],
["Removal","You or another rights holder may submit a removal request. We may ask for enough information to identify the Memory and verify the request. Removal from public display does not require us to erase records that we must retain by law or that are necessary to establish, exercise or defend legal claims."],
["Price and payment","When paid participation is activated, the price shown before payment will be the price applicable to that submission, together with information required by law about applicable taxes."],
["Operator",<>The project is operated by Sonica Broadcast 5.0 SL, NIF / CIF B57754228. Contact: <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a>.</>]]},
es:{title:"TÉRMINOS DE PARTICIPACIÓN",intro:"Las normas que se aplican cuando añades una Memoria a la obra colectiva.",sections:[
["El proyecto","WE ARE SUPERSONICOS es una obra digital colectiva concebida para estar formada por 20.000 memorias reales de la comunidad de Ibiza Sonica. Cada Memoria aceptada recibe un espacio del mismo tamaño. Ningún participante puede comprar una posición mayor, premium o privilegiada."],
["Tu participación","Envías una fotografía vinculada a una experiencia real de Ibiza Sonica, junto con la información solicitada del participante. Eres responsable del contenido enviado y de la exactitud de la información que facilitas."],
["Tus derechos y permisos",<>Conservas los derechos que tengas sobre tu fotografía. Al enviarla, confirmas que eres su propietario o que dispones de los derechos necesarios para compartirla y de los permisos necesarios de las personas identificables que aparezcan en ella.<br/><br/>Concedes a Sonica Broadcast 5.0 SL una licencia no exclusiva para alojar, almacenar, adaptar técnicamente, redimensionar, recortar, reproducir, mostrar y comunicar la fotografía como parte de WE ARE SUPERSONICOS, su mosaico, página de Memoria, Passport y comunicaciones destinadas a presentar, documentar o promocionar el proyecto. Esta licencia no transfiere la propiedad de tu fotografía.</>],
["Normas de participación","No se aceptan menores identificables. No se acepta contenido sexualmente explícito o pornográfico. Se permiten imágenes normales de baño, playa, piscina y vida nocturna. No se acepta violencia gráfica ni contenido de odio, amenazante o claramente abusivo. Podemos rechazar, suspender o retirar contenidos que incumplan estas normas, vulneren derechos o generen un riesgo material de seguridad o legal."],
["Moderación","Los envíos pueden comprobarse automáticamente y, cuando sea necesario, manualmente. Los controles automáticos son una medida de seguridad y no eliminan tu responsabilidad sobre el contenido enviado ni sobre los derechos necesarios para publicarlo."],
["Ubicación en la obra","El proyecto determina la posición de cada Memoria aceptada. La ubicación puede utilizar características visuales como el color y la luz para que las Memorias reconstruyan colectivamente la Imagen Maestra. Igualdad de posición significa igualdad de espacio visual, no el derecho a elegir una ubicación concreta."],
["Retirada","Tú u otro titular de derechos podéis solicitar la retirada de contenido. Podemos pedir información suficiente para identificar la Memoria y verificar la solicitud. La retirada de la visualización pública no nos obliga a eliminar registros que debamos conservar por ley o que sean necesarios para formular, ejercer o defender reclamaciones legales."],
["Precio y pago","Cuando la participación de pago esté activa, el precio mostrado antes del pago será el aplicable a ese envío, junto con la información legalmente exigida sobre los impuestos correspondientes."],
["Operador",<>El proyecto está operado por Sonica Broadcast 5.0 SL, NIF / CIF B57754228. Contacto: <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a>.</>]]}};
export default function Page(){const[lang,setLang]=useState("en");useEffect(()=>setLang(localStorage.getItem("supersonicos-lang")||"en"),[]);const c=copy[lang];return <main className="legalPage"><a className="legalBack" href="/">← WE ARE SUPERSONICOS</a><h1>{c.title}</h1><p className="legalIntro">{c.intro}</p>{c.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</main>}