"use client";
import {useEffect,useState} from "react";
const copy={
en:{title:"LEGAL NOTICE",intro:"Information about the operator of WE ARE SUPERSONICOS.",sections:[
["Operator",<>WE ARE SUPERSONICOS is operated by <strong>Sonica Broadcast 5.0 SL</strong>, NIF / CIF B57754228, a Sociedad Limitada Unipersonal, with registered address at Carretera Eivissa-Sant Antoni, Km 7.200, Nav 1, 07820, Sant Antoni de Portmany, Illes Balears, España.<br/><br/>Contact: <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a><br/><br/>Mercantile Registry details will be added once verified.</>],
["Website","This notice applies to supersonicos.ibizasonica.com and the services made available through it."],
["Intellectual property","The project name, visual identity, website, software, texts and project materials are protected by applicable intellectual property rules. Participant photographs remain subject to the rights described in the Terms of Participation."],
["Applicable law","This website is operated from Spain and is subject to applicable Spanish and European Union law."]]},
es:{title:"AVISO LEGAL",intro:"Información sobre el operador de WE ARE SUPERSONICOS.",sections:[
["Operador",<>WE ARE SUPERSONICOS está operado por <strong>Sonica Broadcast 5.0 SL</strong>, NIF / CIF B57754228, Sociedad Limitada Unipersonal, con domicilio social en Carretera Eivissa-Sant Antoni, Km 7.200, Nav 1, 07820, Sant Antoni de Portmany, Illes Balears, España.<br/><br/>Contacto: <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a><br/><br/>Los datos del Registro Mercantil se añadirán una vez verificados.</>],
["Sitio web","Este aviso se aplica a supersonicos.ibizasonica.com y a los servicios ofrecidos a través del sitio."],
["Propiedad intelectual","El nombre del proyecto, la identidad visual, el sitio web, el software, los textos y los materiales del proyecto están protegidos por la normativa aplicable de propiedad intelectual. Las fotografías de los participantes quedan sujetas a los derechos descritos en los Términos de participación."],
["Legislación aplicable","Este sitio web se opera desde España y está sujeto a la legislación española y de la Unión Europea aplicable."]]}};
export default function Page(){const[lang,setLang]=useState("en");useEffect(()=>setLang(localStorage.getItem("supersonicos-lang")||"en"),[]);const c=copy[lang];return <main className="legalPage"><a className="legalBack" href="/">← WE ARE SUPERSONICOS</a><h1>{c.title}</h1><p className="legalIntro">{c.intro}</p>{c.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</main>}