"use client";
import {useEffect,useState} from "react";
const copy={
en:{title:"REMOVAL & TAKEDOWN",intro:"A direct route to report a Memory or request that content be removed.",sections:[
["When to contact us","Contact us if you submitted a Memory and want to request its removal, if you are identifiable in a photograph and believe it should not be published, if you own rights in a photograph used without permission, or if a Memory appears to breach the Participation Rules."],
["What to send",<>Email <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a> with the subject “WE ARE SUPERSONICOS · Removal request”. Include the Memory number or URL, the reason for the request and enough information for us to understand and, where necessary, verify your connection to the content.</>],
["What happens next","We will assess the request and may temporarily restrict a Memory while it is reviewed. We may ask for additional information where reasonably necessary. Valid requests will be acted on in accordance with applicable law and the project's legal obligations."],
["Urgent safety concerns","If the report concerns a minor, sexual exploitation, credible threats or other urgent safety concerns, state that clearly in the subject and message so it can be prioritised."]]},
es:{title:"RETIRADA DE CONTENIDO",intro:"Una vía directa para denunciar una Memoria o solicitar la retirada de contenido.",sections:[
["Cuándo contactar","Contacta con nosotros si enviaste una Memoria y quieres solicitar su retirada, si eres identificable en una fotografía y consideras que no debería publicarse, si eres titular de derechos sobre una fotografía utilizada sin permiso o si una Memoria parece incumplir las Normas de participación."],
["Qué debes enviar",<>Escribe a <a href="mailto:hello@ibizasonica.com">hello@ibizasonica.com</a> con el asunto “WE ARE SUPERSONICOS · Solicitud de retirada”. Incluye el número o URL de la Memoria, el motivo de la solicitud y la información suficiente para que podamos entender y, cuando sea necesario, verificar tu relación con el contenido.</>],
["Qué ocurre después","Evaluaremos la solicitud y podremos restringir temporalmente una Memoria mientras se revisa. Podemos solicitar información adicional cuando sea razonablemente necesario. Las solicitudes válidas se atenderán de acuerdo con la legislación aplicable y las obligaciones legales del proyecto."],
["Cuestiones urgentes de seguridad","Si la denuncia afecta a un menor, explotación sexual, amenazas creíbles u otras cuestiones urgentes de seguridad, indícalo claramente en el asunto y en el mensaje para que pueda priorizarse."]]}};
export default function Page(){const[lang,setLang]=useState("en");useEffect(()=>setLang(localStorage.getItem("supersonicos-lang")||"en"),[]);const c=copy[lang];return <main className="legalPage"><a className="legalBack" href="/">← WE ARE SUPERSONICOS</a><h1>{c.title}</h1><p className="legalIntro">{c.intro}</p>{c.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</main>}